apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-backend
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: webapp-backend
  template:
    metadata:
      labels:
        app: webapp-backend
    spec:
      containers:
      - name: backend
        image: ${REGISTRY}/demo-webapp-backend:${TAG}
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DB_NAME
          value: demodb
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-frontend
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: webapp-frontend
  template:
    metadata:
      labels:
        app: webapp-frontend
    spec:
      containers:
      - name: frontend
        image: ${REGISTRY}/demo-webapp-frontend:${TAG}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-backend
  namespace: ${NAMESPACE}
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: webapp-backend
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-frontend
  namespace: ${NAMESPACE}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: webapp-frontend