apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: your-gitea-repo-url
    path: k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true